### ISSUE TITLE
Linker iOS Unity 2018.1

### ISSUE THREAD

**Issue by Ratatoeskr1349** [tuneinc/unity-plugin#10]
Under 2018.1 I receive the following error when attempting to archive the project:
ld: library not found for -lPods-Unity-iPhone

I've already tried reinstalling and updating Tune.unitypackage and the google resolver plugin, but nothing works. 
I've also tried switching in the ios resolver settings from "xcode workspace" to "xcode project"

**Comment by john-gu** [comment]
Hi @Ratatoeskr1349, once Unity generates the iOS project, are you opening the **.xcodeproj** or **.xcworkspace** file? CocoaPods requires using the xcworkspace file.

We tried reproducing this issue and the following scenarios worked for us:
- Opened .xcworkspace file where iOS resolver was set to workspace and tried archiving from Xcode
- Opened .xcodeproj file where iOS resolver was set to project and tried archiving from Xcode

**Comment by Ratatoeskr1349** [comment]
@john-gu 

Thank you very much, it worked. We are using the xcodebuild command line tool to archive our projects.
Using xcodebuild -workspace "..." instead of -project worked for us!

**Comment by john-gu** [comment]
Great! Glad to hear this is working for you.
